;-------------------------------------------------------------------------
;
; BBC Micro/Acorn Electron include file for 64tass
;
; Copyright (C) 2026 Tom Seddon
; 
; This program is free software: you can redistribute it and/or
; modify it under the terms of the GNU General Public License as
; published by the Free Software Foundation, either version 3 of the
; License, or (at your option) any later version.
; 
; This program is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
; General Public License for more details.
; 
; You should have received a copy of the GNU General Public License
; along with this program. If not, see
; <https://www.gnu.org/licenses/>.
;
;-------------------------------------------------------------------------

;-------------------------------------------------------------------------
; 
; BASIC stuff
;

basic_line_number: .macro n
                .cerror \n<0||\n>32767,"bad BASIC line number"
                .byte >\n
                .byte <\n
                .endm
                
tokens: .block
AND=$80
DIV=$81
EOR=$82
MOD=$83
OR=$84
ERROR=$85
LINE=$86
OFF=$87
STEP=$88
SPC=$89
TAB_=$8a
ELSE=$8b
THEN=$8c
line_number=$8d
OPENIN=$8e
PTR_rvalue=$8f
PAGE_rvalue=$90
TIME_rvalue=$91
LOMEM_rvalue=$92
HIMEM_rvalue=$93
ABS=$94
ACS=$95
ADVAL=$96
ASC=$97
ASN=$98
ATN=$99
BGET=$9a
COS=$9b
COUNT_rvalue=$9c
DEG=$9d
ERL=$9e
ERR=$9f
EVAL=$a0
EXP=$a1
EXT=$a2
FALSE=$a3
FN=$a4
GET=$a5
INKEY=$a6
INSTR_=$a7
INT=$a8
LEN=$a9
LN=$aa
LOG=$ab
NOT=$ac
OPENUP=$ad
OPENOUT=$ae
PI=$af
POINT_=$b0
POS=$b1
RAD=$b2
RND=$b3
SGN=$b4
SIN=$b5
SQR=$b6
TAN=$b7
TO=$b8
TRUE=$b9
USR=$ba
VAL=$bb
VPOS=$bc
CHR_=$bd
GET_=$be
INKEY_=$bf
LEFT__=$c0
MID__=$c1
RIGHT__=$c2
STR_=$c3
STRING__=$c4
EOF=$c5
AUTO=$c6
DELETE=$c7
LOAD=$c8
LIST=$c9
NEW=$ca
OLD=$cb
RENUMBER=$cc
SAVE=$cd
PTR_lvalue=$cf
PAGE_lvalue=$d0
TIME_lvalue=$d1
LOMEM_lvalue=$d2
HIMEM_lvalue=$d3
SOUND=$d4
BPUT=$d5
CALL=$d6
CHAIN=$d7
CLEAR=$d8
CLOSE=$d9
CLG=$da
CLS=$db
DATA=$dc
DEF=$dd
DIM=$de
DRAW=$df
END=$e0
ENDPROC=$e1
ENVELOPE=$e2
FOR=$e3
GOSUB=$e4
GOTO=$e5
GCOL=$e6
IF=$e7
INPUT=$e8
LET=$e9
LOCAL=$ea
MODE=$eb
MOVE=$ec
NEXT=$ed
ON=$ee
VDU=$ef
PLOT=$f0
PRINT=$f1
PROC=$f2
READ=$f3
REM=$f4
REPEAT=$f5
REPORT=$f6
RESTORE=$f7
RETURN=$f8
RUN=$f9
STOP=$fa
COLOUR=$fb
TRACE=$fc
UNTIL=$fd
WIDTH=$fe
OSCLI=$ff
                .endblock

