;-------------------------------------------------------------------------
;
; BBC Micro/Acorn Electron include file for 64tass
;
; Copyright (C) 2018-9 Tom Seddon
; 
; This program is free software: you can redistribute it and/or
; modify it under the terms of the GNU General Public License as
; published by the Free Software Foundation, either version 3 of the
; License, or (at your option) any later version.
; 
; This program is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
; General Public License for more details.
; 
; You should have received a copy of the GNU General Public License
; along with this program. If not, see
; <https://www.gnu.org/licenses/>.
;
;-------------------------------------------------------------------------


; MOS entry points

                .weak
osrdsc=address($ffb9)
oseven=address($ffbf)
gsinit=address($ffc2)
gsread=address($ffc5)
osfind=address($ffce)
osgbpb=address($ffd1)
osbput=address($ffd4)
osbget=address($ffd7)
osfile=address($ffdd)
osargs=address($ffda)
osrdch=address($ffe0)
osasci=address($ffe3)
osnewl=address($ffe7)
oswrch=address($ffee)
osword=address($fff1)
osbyte=address($fff4)
oscli=address($fff7)
                .endweak
                
;-------------------------------------------------------------------------

; Vectors

                .weak
userv=address($200)
brkv=address($202)
irq1v=address($204)
irq2v=address($206)
cliv=address($208)
bytev=address($20a)
wordv=address($20c)
wrchv=address($20e)
rdchv=address($210)
filev=address($212)
argsv=address($214)
bgetv=address($216)
bputv=address($218)
gbpbv=address($21a)
findv=address($21c)
fscv=address($21e)
eventv=address($220)
uptv=address($222)
vduv=address($226)
keyv=address($228)
insv=address($22a)
remv=address($22c)
cnpv=address($22e)
ind1v=address($230)
ind2v=address($232)
ind3v=address($234)
                .endweak

;-------------------------------------------------------------------------

; Tube transfer reasons

tube_multi_byte_parasite_to_host=0
tube_multi_byte_host_to_parasite=1
tube_multi_pairs_parasite_to_host=2
tube_multi_pairs_host_to_parasite=3
tube_execute=4
tube_256_byte_parasite_to_host=6
tube_256_byte_host_to_parasite=7

;-------------------------------------------------------------------------

;-------------------------------------------------------------------------

; if language_entry is 0, no language entry.
;
; if version_string is empty, no version string.
emit_rom_header .macro language_entry,service_entry,version_number,title_string,version_string,copyright_string
start:
                ; +00 Language entry point
                .if \language_entry!=0
language_entry_flag=$40
                jmp \language_entry
                .else
language_entry_flag=0
                brk
                brk
                brk
                .endif

                ; +03 Service entry point
                jmp \service_entry

                ; +06 ROM type
                .byte $82|language_entry_flag

                ; +07 Copyright offset
                .byte copyright-1-start

                ; +08 Version number
                .byte \version_number

                ; +09 Title string
name:
                .text \title_string
name_end:
                .byte 0
version:
                .text \version_string
version_end:
                .if \version_string!=''
                ; +vv Version string
                .byte 0
                .endif

                ; +nn Copyright string
                .byte 0
copyright:
                .text '(C)'
                .if \copyright_string!=''
                .byte ' ',\copyright_string
                .endif
copyright_end:
                .byte 0
                
                .endm

;-------------------------------------------------------------------------
; 
; 1770/1772. Use .dstruct to put this wherever necessary.
; 
WD177x: .struct
status:
command:
                .fill 1
track:
                .fill 1
sector:
                .fill 1
data:
                .fill 1
                .ends

;-------------------------------------------------------------------------
;
; Tube FIFOs. Use .dstruct to put this wherever necessary.
;
Tube: .struct
fifo1_status: .fill 1
fifo1_data: .fill 1
fifo2_status: .fill 1
fifo2_data: .fill 1
fifo3_status: .fill 1
fifo3_data: .fill 1
fifo4_status: .fill 1
fifo4_data: .fill 1
                .endstruct