;-------------------------------------------------------------------------
;
; BBC Micro/Acorn Electron include file for 64tass
;
; Copyright (C) 2026 Tom Seddon
; 
; This program is free software: you can redistribute it and/or
; modify it under the terms of the GNU General Public License as
; published by the Free Software Foundation, either version 3 of the
; License, or (at your option) any later version.
; 
; This program is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
; General Public License for more details.
; 
; You should have received a copy of the GNU General Public License
; along with this program. If not, see
; <https://www.gnu.org/licenses/>.
;
;-------------------------------------------------------------------------

;-------------------------------------------------------------------------
; Key codes
;
; Should maybe separate these out a bit? Some are B or Master only.
; 
                .weak
key_space=$62
key_comma=$66
key_minus=$17
key_stop=$67
key_slash=$68
key_0=$27
key_1=$30
key_2=$31
key_3=$11
key_4=$12
key_5=$13
key_6=$34
key_7=$24
key_8=$15
key_9=$26
key_colon=$48
key_semicolon=$57
key_at=$47
key_a=$41
key_b=$64
key_c=$52
key_d=$32
key_e=$22
key_f=$43
key_g=$53
key_h=$54
key_i=$25
key_j=$45
key_k=$46
key_l=$56
key_m=$65
key_n=$55
key_o=$36
key_p=$37
key_q=$10
key_r=$33
key_s=$51
key_t=$23
key_u=$35
key_v=$63
key_w=$21
key_x=$42
key_y=$44
key_z=$61
key_left_square_bracket=$38
key_backslash=$78
key_right_square_bracket=$58
key_caret=$18
key_underline=$28
key_escape=$70
key_tab=$60
key_caps_lock=$40
key_ctrl=$1
key_shift_lock=$50
key_shift=$0
key_delete=$59
key_copy=$69
key_return=$49
key_up=$39
key_down=$29
key_left=$19
key_right=$79
key_f0=$20
key_f1=$71
key_f2=$72
key_f3=$73
key_f4=$14
key_f5=$74
key_f6=$75
key_f7=$16
key_f8=$76
key_f9=$77
key_numpad_0=$6a
key_numpad_1=$6b
key_numpad_2=$7c
key_numpad_3=$6c
key_numpad_4=$7a
key_numpad_5=$7b
key_numpad_6=$1a
key_numpad_7=$1b
key_numpad_8=$2a
key_numpad_9=$2b
key_numpad_plus=$3a
key_numpad_minus=$3b
key_numpad_divide=$4a
key_numpad_hash=$5a
key_numpad_multiply=$5b
key_numpad_comma=$5c
key_numpad_return=$3c
key_numpad_delete=$4b
key_numpad_stop=$4c
                
                .endweak

inkey: .sfunction _key,(-(_key+1))&$ff
